### ISSUE TITLE
mein.berlin.de

### ISSUE THREAD

**Issue by bitboxer** [HierBautBerlin/website#17]
# Website

https://mein.berlin.de/projekte/

# API

https://mein.berlin.de/api/plans/

**Comment by ekleinod** [comment]
Mit JSON und Projekte:

https://mein.berlin.de/api/plans?format=json

https://mein.berlin.de/api/projects?format=json

**Comment by bitboxer** [comment]
https://github.com/liqd/a4-meinberlin/blob/master/meinberlin/apps/plans/models.py

and

https://github.com/liqd/a4-meinberlin/blob/master/meinberlin/apps/projects/api.py
